services:
  _defaults:
    autowire: true
    autoconfigure: true

  Symfony\Bundle\MakerBundle\FileManager: "@maker.file_manager"
  Symfony\Bundle\MakerBundle\Generator: "@maker.generator"
  Symfony\Bundle\MakerBundle\Doctrine\DoctrineHelper: "@maker.doctrine_helper"

  Kaudaj\PrestaShopMaker\Maker\MakeCRUDForm:
    arguments:
      - "@maker.file_manager"
      - "@maker.generator"
      - "@maker.doctrine_helper"
    tags:
      - { name: "maker.command" }
  
  Kaudaj\PrestaShopMaker\Maker\MakeMultiLangEntity:
    arguments:
      - "@maker.file_manager"
      - "@maker.doctrine_helper"
    tags:
      - { name: "maker.command" }
