services:
  _defaults:
    autowire: true
    autoconfigure: true

  Symfony\Bundle\MakerBundle\FileManager: "@maker.file_manager"
  Symfony\Bundle\MakerBundle\Generator: "@maker.generator"
  Symfony\Bundle\MakerBundle\Doctrine\DoctrineHelper: "@maker.doctrine_helper"

  Kaudaj\PrestaShopMaker\Maker\AbstractMaker:
    abstract: true
    arguments:
      - "@maker.file_manager"
      - "@maker.generator"
  
  Kaudaj\PrestaShopMaker\Maker\EntityBasedMaker:
    parent: Kaudaj\PrestaShopMaker\Maker\AbstractMaker
    abstract: true
    arguments:
      - "@maker.doctrine_helper"

  Kaudaj\PrestaShopMaker\Maker\MakeCRUDForm:
    parent: 'Kaudaj\PrestaShopMaker\Maker\EntityBasedMaker'
    tags:
      - { name: "maker.command" }
  
  Kaudaj\PrestaShopMaker\Maker\MakeMultiLangEntity:
    parent: 'Kaudaj\PrestaShopMaker\Maker\EntityBasedMaker'
    tags:
      - { name: "maker.command" }
